In [24]:
import numpy as np
import pandas as pd

In [33]:
! pip install TensorFlow
import tensorflow as tf
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler

Requirement already satisfied: TensorFlow in c:\users\hp\anaconda3\conda\lib\site-packages (2.14.0)
Requirement already satisfied: tensorflow-intel==2.14.0 in c:\users\hp\anaconda3\conda\lib\site-packages (from TensorFlow) (2.14.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (2.0.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (23.5.26)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (0.5.4)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (3.7.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (16.0.6)
Requirement already satisfied: ml-dtypes==0.2.0 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (0.2.0)
Requirement already satisfied: numpy>=1.23.5 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (1.24.3)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (3.3.0)
Requirement already satisfied: packaging in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (23.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (4.24.4)
Requirement already satisfied: setuptools in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (68.0.0)
Requirement already satisfied: six>=1.12.0 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (2.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (4.7.1)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (1.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (0.31.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (1.59.0)
Requirement already satisfied: tensorboard<2.15,>=2.14 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (2.14.1)
Requirement already satisfied: tensorflow-estimator<2.15,>=2.14.0 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (2.14.0)
Requirement already satisfied: keras<2.15,>=2.14.0 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorflow-intel==2.14.0->TensorFlow) (2.14.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\hp\anaconda3\conda\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.14.0->TensorFlow) (0.38.4)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->TensorFlow) (2.23.3)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->TensorFlow) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->TensorFlow) (3.4.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->TensorFlow) (2.31.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->TensorFlow) (0.7.1)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\hp\anaconda3\conda\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->TensorFlow) (2.2.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\hp\anaconda3\conda\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->TensorFlow) (5.3.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\hp\anaconda3\conda\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->TensorFlow) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\hp\anaconda3\conda\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->TensorFlow) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\hp\anaconda3\conda\lib\site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->TensorFlow) (1.3.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hp\anaconda3\conda\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->TensorFlow) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\anaconda3\conda\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->TensorFlow) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\anaconda3\conda\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->TensorFlow) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\conda\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->TensorFlow) (2023.7.22)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\hp\anaconda3\conda\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->TensorFlow) (2.1.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\hp\anaconda3\conda\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->TensorFlow) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\hp\anaconda3\conda\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->TensorFlow) (3.2.2)

In [35]:
data=pd.read_csv("C:\\Users\\HP\\Desktop\\Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [36]:
x=data.iloc[:,3:-1].values
y=data.iloc[:,-1].values

In [38]:
le=LabelEncoder()
x[:,1]=le.fit_transform(x[:,1])
x[:,2]=le.fit_transform(x[:,2])

In [40]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [46]:
scaler=StandardScaler()
X_train=scaler.fit_transform(x_train)
X_test=scaler.transform(x_test)

In [48]:
model=tf.keras.Sequential([
    tf.keras.layers.Dense(64,activation='relu',input_dim=X_train.shape[1]),
    tf.keras.layers.Dense(64,activation='relu'),
    tf.keras.layers.Dense(1,activation='sigmoid')
])

In [49]:
loss_fn=tf.keras.losses.BinaryCrossentropy()
metrics=['accuracy']

In [51]:
learning_rate=0.001
momentum=0.9
optimizer=tf.keras.optimizers.SGD(learning_rate=learning_rate,momentum=momentum,nesterov=True)

In [52]:
model.compile(optimizer=optimizer,loss=loss_fn,metrics=metrics)

In [53]:
epochs=10
batch_size=32
model.fit(x_train,y_train,batch_size=batch_size,epochs=epochs,validation_split=0.2)

Epoch 1/10
200/200 [==============================] - 2s 5ms/step - loss: 0.5409 - accuracy: 0.7595 - val_loss: 0.4759 - val_accuracy: 0.7987
Epoch 2/10
200/200 [==============================] - 1s 4ms/step - loss: 0.4755 - accuracy: 0.7936 - val_loss: 0.4530 - val_accuracy: 0.7987
Epoch 3/10
200/200 [==============================] - 1s 5ms/step - loss: 0.4579 - accuracy: 0.7961 - val_loss: 0.4387 - val_accuracy: 0.8037
Epoch 4/10
200/200 [==============================] - 1s 5ms/step - loss: 0.4459 - accuracy: 0.8014 - val_loss: 0.4295 - val_accuracy: 0.8144
Epoch 5/10
200/200 [==============================] - 1s 5ms/step - loss: 0.4376 - accuracy: 0.8091 - val_loss: 0.4226 - val_accuracy: 0.8206
Epoch 6/10
200/200 [==============================] - 1s 5ms/step - loss: 0.4317 - accuracy: 0.8123 - val_loss: 0.4183 - val_accuracy: 0.8269
Epoch 7/10
200/200 [==============================] - 1s 4ms/step - loss: 0.4272 - accuracy: 0.8191 - val_loss: 0.4146 - val_accuracy: 0.8300
Epoch 8/10
200/200 [==============================] - 1s 3ms/step - loss: 0.4230 - accuracy: 0.8223 - val_loss: 0.4112 - val_accuracy: 0.8319
Epoch 9/10
200/200 [==============================] - 1s 4ms/step - loss: 0.4192 - accuracy: 0.8248 - val_loss: 0.4082 - val_accuracy: 0.8331
Epoch 10/10
200/200 [==============================] - 1s 3ms/step - loss: 0.4155 - accuracy: 0.8275 - val_loss: 0.4052 - val_accuracy: 0.8381

In [56]:
test_loss,test_acc=model.evaluate(x_test,y_test)
print('Test Loss:',test_loss)
print('Test Accuracy',test_acc)

63/63 [==============================] - 0s 3ms/step - loss: 0.4033 - accuracy: 0.8315
Test Loss: 0.40326961874961853
Test Accuracy 0.8314999938011169

In [17]:
import numpy as np
import pandas as pd

In [19]:
df=pd.read_csv('C:\\Users\\HP\\Desktop\\Main File\\Project Data\\supply_chain.csv')
df

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,haircare,SKU95,77.903927,65,672,7386.363944,Unknown,15,14,26,...,Mumbai,18,450,26,58.890686,Pending,1.210882,Air,Route A,778.864241
96,cosmetics,SKU96,24.423131,29,324,7698.424766,Non-binary,67,2,32,...,Mumbai,28,648,28,17.803756,Pending,3.872048,Road,Route A,188.742141
97,haircare,SKU97,3.526111,56,62,4370.916580,Male,46,19,4,...,Mumbai,10,535,13,65.765156,Fail,3.376238,Road,Route A,540.132423
98,skincare,SKU98,19.754605,43,913,8525.952560,Female,53,1,27,...,Chennai,28,581,9,5.604691,Pending,2.908122,Rail,Route A,882.198864
99,haircare,SKU99,68.517833,17,627,9185.185829,Unknown,55,8,59,...,Chennai,29,921,2,38.072899,Fail,0.346027,Rail,Route B,210.743009

In [20]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler